### ISSUE TITLE
How to install library without composer

### ISSUE THREAD

**Issue by Andlibmehndi** [AlexaCRM/dynamics-webapi-toolkit#13]
Hi 
can you please guide me that how can I install this dynamics-webapi-toolkit without the composer.

**Comment by wizardist** [comment]
Hi @Andlibmehndi 

It is currently impossible to install the library without Composer because a few other libraries are listed as dependencies.

However, you can install the dependencies with Composer and then move the library with its `vendor` directory elsewhere, just include the `vendor/autoload.php` file in your PHP scripts.

**Comment by Andlibmehndi** [comment]
@wizardist  Thanks
